# Generated by Django 5.2 on 2025-04-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('historial_penal', models.TextField(blank=True, null=True)),
                ('embedding', models.JSONField()),
                ('imagen', models.ImageField(upload_to='personas/')),
            ],
        ),
    ]
