# Generated by Django 5.2 on 2025-04-27 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='person',
            name='historial_penal',
        ),
        migrations.RemoveField(
            model_name='person',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='person',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='uploads/')),
                ('embedding', models.JSONField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recognition.person')),
            ],
        ),
    ]
