# Generated by Django 5.2 on 2025-04-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_remove_person_embedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
