# Generated by Django 5.2 on 2025-04-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_alter_faceimage_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='genero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
